return {
    [1] = "Remember to stay hydrated!",
    [2] = "Take breaks when gaming to avoid eye strain.",
    [3] = "Communication is key in team games.",
    [4] = "Practice makes perfect - keep improving!",
    [5] = "Have fun and enjoy the game!",
    [6] = "33% of the time you do something, you will love it.\n33% of the time you will work for it.\n33% of the time you will question it.",
    [7] = "Your thoughts control your feelings.\nYour feelings control your passions & actions.\nYour actions control your life.",
    [8] = "Your friends and acquaintances will determine the quality and direction of your life.",
    [9] = "Whatever your goal or dream is - it *has* to come out of your mouth without *fear* of what might happen.",
    [10] = "Anything & everything is possible.",
    [11] = "Growth doesn't just happen. Be intentional about ***how*** it happens.",
    [12] = "If you aim at nothing, you will hit it every time.",
    [13] = "Goals are the destination.\nGrowth is the vehicle.",
    [14] = "Practice long-term thinking:\n\nWhy is it hard?\n*We are impatient.*\nWork intentionally.\n\nWhere is the *space* between you and who you want to become?",
    [15] = "Growth is not a single event.\n\nCreate action items - tangible & objective.\nSeek out concepts to *pass them along.*\nAre you *prepared* to make a new connection?",
    [16] = "We will eat the fruit of our words.\nWhat seeds are you planting?",
    [17] = "We speak life over people by showing them their *possibility*.",
    [18] = "Great relationships are not found, they are developed.",
    [19] = "\"I know you are here for more.\"",
    [20] = "*See: the 5 stages of change*",
    [21] = "You have built everything you see before you.\nWhat you listen to & who you listen to is what you become.",
    [22] = "Trying to *excel* your weaknesses is not a good use of your time.",
    [23] = "Your emotions are liars.",
    [24] = "1. Are you enjoying it?\n2. Are you getting better?\n3. Is it worth the effort?\n\nIf at least 2 out of these 3 are `yes`, then you're probably fine.\nOtherwise, look inwards.",
    [25] = "The right motives:\n- Keep you from manipulating.\n- Strengthen you during adversity.\n- Make you credible.\n- Allow you to serve others."
}