return {
    'cat',
    'dog',
    'rabbit',
    'horse',
    'sheep',
    'rat',
    'bird',
    'fish',
    'eel',
    'moose',

    'totem poles',
    'jargon',
    'teapots',
    'cookware',
    'box tops',
    'vinyls',
    'fabrics',
    'townhomes',
    'condos',
    'investments',
    'tadpoles',
    'light fixtures',
    'toilets',
    'bug',
    'doge',
    'superheroes',
    'comics',
    'screens',
    'tests',
    'electrons',
    'atoms',
    'spaceships',
    'swords',
    'knives',
    'hoodlums',
    'portals',
    'planets',
    'hitboxes',
    'hurtboxes',
    'fighting games',
    'MOBAs',
    'battle royale games',
    'silverware',
    'villains',
    'supervillains',
    'haters',
    'stalker-fans',
    'snowflakes',
    'industries',
    'cities',
    'workplaces',
    'grandmas',
    'relatives',
    'family parties',
    'properties',
    'board games',
    'dungeons',
    'dinosaurs',
    'chickens',
    'dragons',
    'idiots',
    'scientists',
    'marine biologists',
    'squids',
    'side streets',
    'street smarts',
    'burgers',
    'shovels',
    'juice',
    'cars',
    'fingers',
    'guitar strings',
    'computers',
    'graphics cards',
    'processors',
    'playing cards',
    'roguelikes',
    'strategy games',
    'chess boards',
    'checkers players',
    'chicken feet',
}